### ISSUE TITLE
Caused by: java.lang.NoSuchMethodError: com.fasterxml.jackson.dataformat.yaml.YAMLFactory._decorate(Ljava/io/InputStream;Lcom/fasterxml/jackson/core/io/IOContext;)Ljava/io/InputStream;

### ISSUE THREAD

**Issue by kchvilyov** [aleksandy/petrovich-java#1]
Caused by: java.lang.NoSuchMethodError: com.fasterxml.jackson.dataformat.yaml.YAMLFactory._decorate(Ljava/io/InputStream;Lcom/fasterxml/jackson/core/io/IOContext;)Ljava/io/InputStream;
	at com.fasterxml.jackson.dataformat.yaml.YAMLFactory.createParser(YAMLFactory.java:306) [jackson-dataformat-yaml-2.5.2.jar:2.5.2]
	at com.fasterxml.jackson.dataformat.yaml.YAMLFactory.createParser(YAMLFactory.java:14) [jackson-dataformat-yaml-2.5.2.jar:2.5.2]
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2080) [jackson-databind-2.2.3.jar:]
	at com.github.aleksandy.petrovich.rules.loader.YamlRulesLoader.load(YamlRulesLoader.java:30) [petrovich-1.2.1.jar:]
	at com.github.aleksandy.petrovich.rules.RulesProvider.<init>(RulesProvider.java:11) [petrovich-1.2.1.jar:]
	at com.github.aleksandy.petrovich.Petrovich.<init>(Petrovich.java:19) [petrovich-1.2.1.jar:]
	at com.github.aleksandy.petrovich.Petrovich.<init>(Petrovich.java:15) [petrovich-1.2.1.jar:]

**Comment by kchvilyov** [comment]
<jackson.version>2.7.4</jackson.version>
Java 1.7

**Comment by kchvilyov** [comment]
The same for <jackson.version>2.2.3</jackson.version>

**Comment by kchvilyov** [comment]
Code:         Petrovich morpher = new Petrovich();

**Comment by kchvilyov** [comment]
Have fixed by correct using <jackson.version>2.7.4</jackson.version> on the server.
